version: "3.12.4"

services:

  app:
    build: .
    container_name: sqlagent-app
    env_file:
      - .env
    command: python app.py
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: sqlagent-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: agentdb
    ports:
      - "5432:5432"
